"""End-to-end subprocess tests for hook.sh.

Pipes synthetic Claude Code tool-call JSON via stdin and asserts on exit
codes + stdout/stderr shape.
"""

import json
import subprocess
from pathlib import Path

import pytest

HOOK = Path(__file__).resolve().parent.parent / "hook.sh"


def _write_project(tmp_path: Path, file_contents: dict[str, str], rule_yaml: str) -> Path:
    """Create a tmp project with .bully.yml + source files."""
    (tmp_path / ".bully.yml").write_text(rule_yaml)
    for rel, body in file_contents.items():
        p = tmp_path / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(body)
    return tmp_path


def _run_hook(stdin_text: str, cwd: Path) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["bash", str(HOOK)],
        input=stdin_text,
        capture_output=True,
        text=True,
        timeout=15,
        cwd=str(cwd),
    )


SIMPLE_RULE_YAML = (
    "rules:\n"
    "  no-console-log:\n"
    '    description: "Do not call print (simulated no-console)"\n'
    "    engine: script\n"
    '    scope: "*.py"\n'
    "    severity: error\n"
    "    script: \"grep -n 'print(' {file} && exit 1 || exit 0\"\n"
    "  inline-single-use:\n"
    '    description: "Semantic rule about inline-single-use vars"\n'
    "    engine: semantic\n"
    '    scope: "*.py"\n'
    "    severity: warning\n"
)


# ---------------------------------------------------------------------------
# 1. Edit on clean file -> exit 0, stdout is either empty or hookSpecificOutput
# ---------------------------------------------------------------------------


def test_edit_clean_file_exits_zero(tmp_path):
    project = _write_project(
        tmp_path,
        {"src/clean.py": "def foo():\n    return 1\n"},
        SIMPLE_RULE_YAML,
    )
    target = project / "src" / "clean.py"
    payload = {
        "tool_name": "Edit",
        "tool_input": {
            "file_path": str(target),
            "old_string": "return 1",
            "new_string": "return 1",
        },
    }
    r = _run_hook(json.dumps(payload), project)
    assert r.returncode == 0, f"stderr={r.stderr}"
    stdout = r.stdout.strip()
    if stdout:
        data = json.loads(stdout)
        assert "hookSpecificOutput" in data
        assert data["hookSpecificOutput"]["hookEventName"] == "PostToolUse"
        assert isinstance(data["hookSpecificOutput"]["additionalContext"], str)


# ---------------------------------------------------------------------------
# 2. Edit on violating file -> exit 2 + blocked stderr
# ---------------------------------------------------------------------------


def test_edit_violating_file_exits_two(tmp_path):
    project = _write_project(
        tmp_path,
        {"src/dirty.py": "def foo():\n    print('bad')\n    return 1\n"},
        SIMPLE_RULE_YAML,
    )
    target = project / "src" / "dirty.py"
    payload = {
        "tool_name": "Edit",
        "tool_input": {
            "file_path": str(target),
            "old_string": "return 1",
            "new_string": "return 1",
        },
    }
    r = _run_hook(json.dumps(payload), project)
    assert r.returncode == 2, f"expected exit 2, got {r.returncode}; stderr={r.stderr}"
    assert "AGENTIC LINT -- blocked" in r.stderr
    assert "no-console-log" in r.stderr


# ---------------------------------------------------------------------------
# 3. Write tool on auto-generated file -> exit 0, no output (short-circuit)
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "filename",
    [
        "package-lock.json",
        "yarn.lock",
        "Cargo.lock",
        "foo.min.js",
    ],
)
def test_write_autogenerated_file_short_circuit(tmp_path, filename):
    project = _write_project(tmp_path, {filename: "generated\n"}, SIMPLE_RULE_YAML)
    target = project / filename
    payload = {
        "tool_name": "Write",
        "tool_input": {
            "file_path": str(target),
            "content": "generated\n",
        },
    }
    r = _run_hook(json.dumps(payload), project)
    assert r.returncode == 0, f"stderr={r.stderr}"
    assert r.stdout.strip() == "", f"expected empty stdout, got: {r.stdout!r}"


# ---------------------------------------------------------------------------
# 4. Malformed JSON on stdin -> non-crash, clean exit (pipeline treats as no-op)
# ---------------------------------------------------------------------------


def test_malformed_json_does_not_crash(tmp_path):
    project = _write_project(
        tmp_path,
        {"src/clean.py": "def foo():\n    return 1\n"},
        SIMPLE_RULE_YAML,
    )
    # Malformed JSON: pipeline falls back to "diff" interpretation,
    # but has no file_path -> exits 0 without crashing.
    r = _run_hook("{not valid json at all", project)
    # Must not raise a Python traceback
    assert "Traceback" not in r.stderr
    # Should not crash with a non-zero/nonstandard exit (anything not 0 or 2 here
    # is fine if the error is reported; we assert it at least doesn't throw).
    assert r.returncode in (0, 1, 2), f"unexpected exit {r.returncode}: {r.stderr}"


def test_empty_stdin_exits_cleanly(tmp_path):
    project = _write_project(
        tmp_path,
        {"src/clean.py": "def foo():\n    return 1\n"},
        SIMPLE_RULE_YAML,
    )
    r = _run_hook("", project)
    assert r.returncode == 0
    assert "Traceback" not in r.stderr


# ---------------------------------------------------------------------------
# 5. File outside a repo with .bully.yml -> exit 0 silently
# ---------------------------------------------------------------------------


def test_no_config_found_exits_zero(tmp_path):
    # No .bully.yml in tmp_path
    target = tmp_path / "src" / "clean.py"
    target.parent.mkdir(parents=True)
    target.write_text("print('hi')\n")
    payload = {
        "tool_name": "Edit",
        "tool_input": {
            "file_path": str(target),
            "old_string": "hi",
            "new_string": "hi",
        },
    }
    r = _run_hook(json.dumps(payload), tmp_path)
    assert r.returncode == 0
    assert r.stdout.strip() == ""


# ---------------------------------------------------------------------------
# 6. Semantic eval contract: dict-shaped JSON additionalContext with excerpts
# ---------------------------------------------------------------------------


SEMANTIC_RULE_WITH_CONTEXT_YAML = (
    "rules:\n"
    "  needs-context:\n"
    '    description: "Semantic rule that wants surrounding context"\n'
    "    engine: semantic\n"
    '    scope: "*.py"\n'
    "    severity: warning\n"
    "    context:\n"
    "      lines: 3\n"
)


def test_semantic_eval_emits_dict_payload_with_excerpt(tmp_path):
    """The PostToolUse hook contract (skills/bully/SKILL.md §32):

    `additionalContext` MUST start with the AGENTIC LINT header and carry
    a JSON body with `file`, `diff`, `passed_checks`, `evaluate`, and a
    `_evaluator_input` string that includes <EXCERPT_FOR_RULE> when the
    rule requested context. Regression guard: re-rendering from the
    stripped outer `evaluate` array used to drop excerpts entirely.
    """
    project = _write_project(
        tmp_path,
        {
            "src/foo.py": (
                "def foo():\n"
                "    a = 1\n"
                "    b = 2\n"
                "    c = 3\n"
                "    d = 4\n"
                "    return a + b + c + d\n"
            )
        },
        SEMANTIC_RULE_WITH_CONTEXT_YAML,
    )
    target = project / "src" / "foo.py"
    # Multi-line edit: the can-match filter (`_can_match_diff`) drops
    # semantic rules when fewer than two lines were added, so ensure
    # the hunk crosses that threshold.
    payload = {
        "tool_name": "Edit",
        "tool_input": {
            "file_path": str(target),
            "old_string": "    d = 4\n    return a + b + c + d",
            "new_string": "    d = 4\n    e = 5\n    f = 6\n    return a + b + c + d + e + f",
        },
    }
    r = _run_hook(json.dumps(payload), project)
    assert r.returncode == 0, f"stderr={r.stderr}"
    assert r.stdout.strip(), f"expected hookSpecificOutput on stdout; stderr={r.stderr!r}"

    data = json.loads(r.stdout)
    assert data["hookSpecificOutput"]["hookEventName"] == "PostToolUse"
    ctx = data["hookSpecificOutput"]["additionalContext"]
    assert isinstance(ctx, str)

    header = "AGENTIC LINT SEMANTIC EVALUATION REQUIRED:"
    assert ctx.startswith(header), f"missing header; got: {ctx[:80]!r}"

    body_text = ctx[len(header):].lstrip()
    body = json.loads(body_text)

    for key in ("file", "diff", "passed_checks", "evaluate", "_evaluator_input"):
        assert key in body, f"missing key {key!r} in payload"

    rule = next((r for r in body["evaluate"] if r["id"] == "needs-context"), None)
    assert rule is not None, f"rule missing from evaluate: {body['evaluate']}"
    assert rule.get("context", {}).get("lines") == 3

    eval_input = body["_evaluator_input"]
    assert isinstance(eval_input, str) and eval_input.startswith("SEMANTIC EVALUATION REQUIRED")
    assert '<EXCERPT_FOR_RULE rule="needs-context">' in eval_input, (
        "excerpt block missing from _evaluator_input -- "
        "hook is likely re-rendering from the stripped outer rules"
    )
    assert "<TRUSTED_POLICY>" in eval_input
    assert "<UNTRUSTED_EVIDENCE>" in eval_input


# ---------------------------------------------------------------------------
# 7. Hook is a thin shim -- exits via python3 exec
# ---------------------------------------------------------------------------


def test_hook_script_exists_and_is_thin():
    """hook.sh should be a thin dispatch shim (no jq, no STDOUT_FILE dance).

    Bumped from 12 to 18 when Stop / SubagentStop dispatch was added in
    PR 3. The `case ${1:-post-tool-use}` block now has four arms (session-start,
    stop, subagent-stop, post-tool-use|*) but still routes by first arg with
    no parsing or logic.
    """
    content = HOOK.read_text()
    lines = [line for line in content.splitlines() if line.strip()]
    assert len(lines) <= 18, f"hook.sh grew: {len(lines)} non-blank lines"
    assert "jq" not in content
    assert "--hook-mode" in content
    assert "session-start" in content
    assert "stop" in content
    assert "subagent-stop" in content
